### ISSUE TITLE
Handlebars helpers doesn't work with parameters

### ISSUE THREAD

**Issue by bioform** [bminer/meteor-blade#3]
since you have "helpers-hack.js" file
all custom helpers get empty parameters!
I spent a lot of time to find it... Still thinking how to fix it....

[boil over]

**Comment by bminer** [comment]
I know... `helpers-hack.js` is a very sad file...

Let me know what you come up with... as time permits, I will try to revisit many of these issues.

**Comment by bioform** [comment]
at current point I temporrary moved to [jade-handlebars](git://github.com/SimonDegraeve/meteor-jade-handlebars.git)

**Comment by bminer** [comment]
@bioform - Yeah... I think this issue has to be resolved by the Meteor development team.  Handlebars is fairly deeply integrated into Meteor.  Helpers is one of those things.  `helpers-hack.js` gets some of the helpers functionality to work in Meteor, but not all (i.e. helpers with parameters)....

See https://github.com/meteor/meteor/issues/790 for more info.

**Comment by bioform** [comment]
When I removed this file(just for tests) - everithing worked OK.
May be it will be better to remove it at all ?

**Comment by bminer** [comment]
Hmmm.... I thought that this file was needed to allow other Handlebars helpers to work?

**Comment by bioform** [comment]
I guess at current point it is useless...

**Comment by lalomartins** [comment]
this works for me (too small to bother with a fork): line 14:
return helper.apply(arguments);

**Comment by bminer** [comment]
@lalomartins - What about simply `partial[helperName] = helper;`??  See latest commit: db93947e636ace473b59f7804bbc7174ca1f94cd

**Comment by lalomartins** [comment]
that sounds like it should work, I'll test it later today and confirm.

**Comment by bminer** [comment]
Cool, thanks!  Let me know, and if it works, I will push the changes to Meteorite.

**Comment by lalomartins** [comment]
As far as I can see that works for me.

**Comment by bminer** [comment]
Pushed to meteorite
